Repository Project-PotionMaker/PotionMaker, pull requests merged in 2025-08, with the labels that each got.

#90 Style | 대기화면 퇴장팝업 추가
  Assets/01. Scenes/2_WaitingScene.unity
  Assets/03. Prefabs/Scene UI/WaitingScene/Popup.meta
  Assets/03. Prefabs/Scene UI/WaitingScene/Popup/Popup_ExitConfirm.prefab
  Assets/03. Prefabs/Scene UI/WaitingScene/Popup/Popup_ExitConfirm.prefab.meta
  Assets/03. Prefabs/Scene UI/WaitingScene/UI_WaitingScene.prefab
Labels: 🍉Mingyu, Style

#92 Feat | 신문UI 및 평판티어에 따른 포션 티어 리스트 추가
  Assets/02. Scripts/02-04. Potion/DailyPotion/DailyPotionPicker.cs
  Assets/02. Scripts/02-07. NewsPaper.meta
  Assets/02. Scripts/02-07. NewsPaper/UI_NewsPaper.cs
  Assets/02. Scripts/02-07. NewsPaper/UI_NewsPaper.cs.meta
  Assets/02. Scripts/02-07. NewsPaper/UI_SlotDailyPotion.cs
  Assets/02. Scripts/02-07. NewsPaper/UI_SlotDailyPotion.cs.meta
  Assets/02. Scripts/02-15. Reputation/3. Manager/ReputationManager.cs
  Assets/02. Scripts/02. Phase/PhaseManager.cs
  Assets/03. Prefabs/Scene UI/GameScene/1. Preparing Phase.meta
  Assets/03. Prefabs/Scene UI/GameScene/1. Preparing Phase/Newspaper.meta
  Assets/03. Prefabs/Scene UI/GameScene/1. Preparing Phase/Newspaper/Popup_Newspaper.prefab
  Assets/03. Prefabs/Scene UI/GameScene/1. Preparing Phase/Newspaper/Popup_Newspaper.prefab.meta
  Assets/03. Prefabs/Scene UI/GameScene/1. Preparing Phase/Newspaper/Slot.meta
  Assets/03. Prefabs/Scene UI/GameScene/1. Preparing Phase/Newspaper/Slot/Slot_DailyPotion.prefab
  Assets/03. Prefabs/Scene UI/GameScene/1. Preparing Phase/Newspaper/Slot/Slot_DailyPotion.prefab.meta
  Assets/03. Prefabs/Scene UI/GameScene/2. Practicing Phase.meta
  Assets/03. Prefabs/Scene UI/GameScene/3. Serving Phase.meta
  Assets/03. Prefabs/Scene UI/GameScene/4. Ending Phase.meta
Labels: Feature, Refactor, 🍉Mingyu

#93 Feat | 평판 시스템 변화량 관리 로직 구현
  Assets/02. Scripts/02-15. Reputation/1. Domain/Reputation.cs
  Assets/02. Scripts/02-15. Reputation/1. Domain/ReputationDTO.cs
  Assets/02. Scripts/02-15. Reputation/3. Manager/ReputationManager.cs
Labels: Feature, 🍉Mingyu

#97 Hotfix | 테스트 중 발생한 PotionDataList NullReference 문제 해결
  Assets/02. Scripts/02-04. Potion/DailyPotion/DailyPotionPicker.cs
  Assets/02. Scripts/02. Phase/PhaseManager.cs
Labels: Fix, 🍉Mingyu

#102 Fix | 함수명 수정
  Assets/01. Scenes/Prototype Scenes/KYS_CopyTestScene.unity
  Assets/01. Scenes/Prototype Scenes/KYS_CopyTestScene.unity.meta
  Assets/02. Scripts/02-10. Customer/CustomerManager/CustomerManager.cs
Labels: Fix, 🍎Yeongsuk

#103 Fix | 정산UI방세 - 심형준
  Assets/02. Scripts/02-09. Rent/1.Domain/Rent.cs
  Assets/02. Scripts/02-09. Rent/1.Domain/RentDTO.cs
  Assets/02. Scripts/02-09. Rent/3.Manager/RentManager.cs
  Assets/02. Scripts/02.-04. Sales/4.UI/UI_DaySummary.cs
Labels: Fix, 🧃Hyeongjun

#105 Feat | 정산UI평판변화량 - 심형준
  Assets/02. Scripts/02-15. Reputation/1. Domain/Reputation.cs
  Assets/02. Scripts/02.-04. Sales/4.UI/UI_DaySummary.cs
Labels: Feature, 🧃Hyeongjun

#112 Style | 티어2, 3 포션 상점 레이아웃 설계
  Assets/01. Scenes/3_2_GameScene_Tier2PotionShop.meta
  Assets/01. Scenes/3_2_GameScene_Tier2PotionShop.unity
  Assets/01. Scenes/3_2_GameScene_Tier2PotionShop.unity.meta
  Assets/01. Scenes/3_2_GameScene_Tier2PotionShop/NavMesh-NavMeshMap_Tier2.asset
  Assets/01. Scenes/3_2_GameScene_Tier2PotionShop/NavMesh-NavMeshMap_Tier2.asset.meta
  Assets/01. Scenes/3_3_GameScene_Tier3PotionShop.meta
  Assets/01. Scenes/3_3_GameScene_Tier3PotionShop.unity
  Assets/01. Scenes/3_3_GameScene_Tier3PotionShop.unity.meta
  Assets/01. Scenes/3_3_GameScene_Tier3PotionShop/NavMesh-NavMeshMap_Tier3.asset
  Assets/01. Scenes/3_3_GameScene_Tier3PotionShop/NavMesh-NavMeshMap_Tier3.asset.meta
Labels: 🍉Mingyu, Style

#113 Feat | 도감 시스템 구현 - 박우영
  Assets/01. Scenes/Prototype Scenes/WYP_RecipeUIScene.unity
  Assets/01. Scenes/Prototype Scenes/WYP_RecipeUIScene.unity.meta
  Assets/02. Scripts/02-01. Common/PotionHouse.cs
  Assets/02. Scripts/02-11. Recipe.meta
  Assets/02. Scripts/02-11. Recipe/4. UI.meta
  Assets/02. Scripts/02-11. Recipe/4. UI/UI_RecipeBook.cs
  Assets/02. Scripts/02-11. Recipe/4. UI/UI_RecipeBook.cs.meta
  Assets/02. Scripts/02-11. Recipe/4. UI/UI_RecipePage.cs
  Assets/02. Scripts/02-11. Recipe/4. UI/UI_RecipePage.cs.meta
  Assets/02. Scripts/02-11. Recipe/RecipeManager.cs
  Assets/02. Scripts/02-11. Recipe/RecipeManager.cs.meta
  Assets/03. Prefabs/Recipe.meta
  Assets/03. Prefabs/Recipe/RecipeManager.prefab
  Assets/03. Prefabs/Recipe/RecipeManager.prefab.meta
  Assets/03. Prefabs/Recipe/UI_RecipeBook.prefab
  Assets/03. Prefabs/Recipe/UI_RecipeBook.prefab.meta
  Assets/04. Images/Ingredient.meta
  Assets/04. Images/Ingredient/BlueGreenMoss.png
  Assets/04. Images/Ingredient/BlueGreenMoss.png.meta
  Assets/04. Images/Ingredient/PointGrass.png
  Assets/04. Images/Ingredient/PointGrass.png.meta
  Assets/04. Images/Recipe.meta
  Assets/04. Images/Recipe/Book-Photoroom.png
  Assets/04. Images/Recipe/Book-Photoroom.png.meta
  Assets/04. Images/Recipe/Book.png
  Assets/04. Images/Recipe/Book.png.meta
  Assets/04. Images/Recipe/EmptyPage.png
  Assets/04. Images/Recipe/EmptyPage.png.meta
  Assets/04. Images/Recipe/EmptyPage2.png
  Assets/04. Images/Recipe/EmptyPage2.png.meta
  Assets/04. Images/Recipe/NewsPaper.png
  Assets/04. Images/Recipe/NewsPaper.png.meta
  Assets/04. Images/Recipe/Page.png
  Assets/04. Images/Recipe/Page.png.meta
  Assets/20. External Assets/Layer Lab/GUI Pro-FantasyRPG/Prefabs/Prefabs_Component_Frames/_Prefabs_Frames.prefab
  Assets/20. External Assets/Layer Lab/GUI Pro-FantasyRPG/Prefabs/Prefabs_DemoScene_Panels/Equipment.prefab
  Assets/20. External Assets/Layer Lab/GUI Pro-FantasyRPG/Prefabs/Prefabs_DemoScene_Panels/Shop_Chest.prefab
  Assets/TextMesh Pro/Resources/TMP Settings.asset
Labels: Add, Feature, 🍞Uyeong

#114 Style | 티어1 포션상점 레이아웃 설계
  Assets/01. Scenes/3_1_GameScene_Tier1PotionShop.meta
  Assets/01. Scenes/3_1_GameScene_Tier1PotionShop.unity
  Assets/01. Scenes/3_1_GameScene_Tier1PotionShop.unity.meta
  Assets/01. Scenes/3_1_GameScene_Tier1PotionShop/NavMesh-NavMeshMap_Tier1.asset
  Assets/01. Scenes/3_1_GameScene_Tier1PotionShop/NavMesh-NavMeshMap_Tier1.asset.meta
Labels: 🍉Mingyu, Style

#125 Feat | 홀 영역 경로 탐색 알고리즘
  Assets/01. Scenes/Prototype Scenes/LSJ_PrototypeScene.unity
  Assets/02. Scripts/02-05. Grid/1. Domain/GridData.cs
  Assets/02. Scripts/02-05. Grid/3. Service/GridManager.cs
  Assets/02. Scripts/02-05. Grid/3. Service/HallAreaPathFinder.cs
  Assets/02. Scripts/02-05. Grid/3. Service/HallAreaPathFinder.cs.meta
  Assets/02. Scripts/02-05. Grid/LayoutEditing/GridInfo.cs
Labels: Feature, 🍉Mingyu

#128 Feat | Camera 이동 - 박우영
  Assets/01. Scenes/Prototype Scenes/WYP_PrototypeScene.unity
  Assets/02. Scripts/02-03. Player/CameraZoneSwitcher.cs
  Assets/02. Scripts/02-03. Player/CameraZoneSwitcher.cs.meta
  Assets/03. Prefabs/Door.prefab
  Assets/03. Prefabs/Door.prefab.meta
  Assets/03. Prefabs/InGameCamera.prefab
  Assets/03. Prefabs/InGameCamera.prefab.meta
  Assets/03. Prefabs/Player/Player.prefab
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/DynamicsManager.asset
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/TagManager.asset
Labels: Add, Feature, 🍞Uyeong, Style

#129 Feat | 기구 상호작용 진행도 UI 분리 및 동기화 - 심형준
  Assets/01. Scenes/Prototype Scenes/LSJ_PrototypeScene.unity
  Assets/02. Scripts/02-06. Structure/Machine/UI_Machine.cs
  Assets/03. Prefabs/Furniture/Machine.prefab
  ProjectSettings/EditorBuildSettings.asset
Labels: Feature, 🧃Hyeongjun

#133 Fix | Item 중심점 재설정 / 그리드 시스템 수정
  Assets/02. Scripts/02-03. Player/Ability/PlayerPickupAbility.cs
  Assets/02. Scripts/02-05. Grid/1. Domain/GridData.cs
  Assets/02. Scripts/02-05. Grid/3. Service/GridManager.cs
  Assets/02. Scripts/02-05. Grid/3. Service/States/PlacementState.cs
  Assets/03. Prefabs/Furniture/Furniture.prefab
  Assets/03. Prefabs/Furniture/Machine.prefab
  Assets/03. Prefabs/Furniture/Storage.prefab
  Assets/03. Prefabs/Potion Process/Ingredients/Ingredient_Base.prefab
  Assets/03. Prefabs/Potion Process/Outputs/Output_Base.prefab
  Assets/03. Prefabs/Potion Process/Potions/Potion_Base.prefab
Labels: Fix, 🍪Sangjin

#137 Feat 포션티어별로랜덤으로가져오기
  Assets/01. Scenes/Prototype Scenes/LSJ_PrototypeScene.unity
  Assets/02. Scripts/02-04. Potion/CraftItem/IngredientItem/IngredientItem.cs
  Assets/02. Scripts/02-04. Potion/CraftItem/OutputItem/OutputItem.cs
  Assets/02. Scripts/02-04. Potion/CraftItem/PotionItem/PotionItem.cs
  Assets/02. Scripts/02-05. Grid/3. Service/GridManager.cs
  Assets/02. Scripts/02-10. Customer/Customer.cs
  Assets/02. Scripts/02-10. Customer/CustomerAbility/CustomerEndurance.cs
  Assets/02. Scripts/02-10. Customer/CustomerAbility/CustomerMove.cs
  Assets/02. Scripts/02-10. Customer/CustomerManager/CustomerManager.cs
  Assets/02. Scripts/02-10. Customer/CustomerUI/UI_Customer.cs
  Assets/02. Scripts/02. Phase/PhaseManager.cs
  Assets/03. Prefabs/Furniture/Furniture.prefab
Labels: Feature, Fix, 🍎Yeongsuk

#134 Feat | 포션상점 데이터 저장/로드 시스템
  Assets/01. Scenes/1_LobbyScene.unity
  Assets/02. Scripts/02-01. Common/PotionHouse.cs
  Assets/02. Scripts/02-03. Currency/1.Domain/Currency.cs
  Assets/02. Scripts/02-03. Currency/1.Domain/CurrencyDTO.cs
  Assets/02. Scripts/02-03. Currency/3.Manager/CurrencyManager.cs
  Assets/02. Scripts/02-05. Grid/1. Domain/GridData.cs
  Assets/02. Scripts/02-05. Grid/1. Domain/GridDataDTO.cs
  Assets/02. Scripts/02-05. Grid/1. Domain/Placement.cs
  Assets/02. Scripts/02-05. Grid/1. Domain/PlacementDTO.cs
  Assets/02. Scripts/02-05. Grid/1. Domain/SaveData.meta
  Assets/02. Scripts/02-05. Grid/1. Domain/SaveData/GridSaveData.cs
  Assets/02. Scripts/02-05. Grid/1. Domain/SaveData/GridSaveData.cs.meta
  Assets/02. Scripts/02-05. Grid/1. Domain/SaveData/GridSaveDataDTO.cs
  Assets/02. Scripts/02-05. Grid/1. Domain/SaveData/GridSaveDataDTO.cs.meta
  Assets/02. Scripts/02-05. Grid/3. Service/GridManager.cs
  Assets/02. Scripts/02-15. Reputation/1. Domain/Reputation.cs
  Assets/02. Scripts/02-15. Reputation/1. Domain/ReputationDTO.cs
  Assets/02. Scripts/02-15. Reputation/3. Manager/ReputationManager.cs
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/RoomInfo/RoomInfoHandler.cs
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/ShopInfo/1. Domain.meta
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/ShopInfo/1. Domain/ShopInfo.cs
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/ShopInfo/1. Domain/ShopInfo.cs.meta
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/ShopInfo/1. Domain/Specification.meta
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/ShopInfo/1. Domain/Specification/ShopInfoSpecification.cs
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/ShopInfo/1. Domain/Specification/ShopInfoSpecification.cs.meta
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/ShopInfo/2. Repository.meta
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/ShopInfo/2. Repository/IShopInfoSaveable.cs
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/ShopInfo/2. Repository/IShopInfoSaveable.cs.meta
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/ShopInfo/2. Repository/ShopInfoDTO.cs
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/ShopInfo/2. Repository/ShopInfoDTO.cs.meta
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/ShopInfo/2. Repository/ShopInfoRepository.cs
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/ShopInfo/2. Repository/ShopInfoRepository.cs.meta
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/ShopInfo/3. Manager.meta
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/ShopInfo/3. Manager/ShopInfoHandler.cs
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/ShopInfo/3. Manager/ShopInfoHandler.cs.meta
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/ShopInfo/3. Manager/ShopInfoManager.cs
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/ShopInfo/3. Manager/ShopInfoManager.cs.meta
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/ShopInfo/ShopInfo.cs
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/ShopInfo/UI.meta
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/ShopInfo/UI/CreatePopup.cs
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/ShopInfo/UI/CreatePopup.cs.meta
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/ShopInfo/UI/Slot.meta
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/ShopInfo/UI/Slot/ShopInfoSlot.cs
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/ShopInfo/UI/Slot/ShopInfoSlot.cs.meta
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/ShopInfo/UI/Slot/UI_ShopInfoSlot.cs
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/ShopInfo/UI/Slot/UI_ShopInfoSlot.cs.meta
  Assets/02. Scripts/02. Phase/PhaseManager.cs
  Assets/02. Scripts/02.-04. Sales/1.Domain/Sales.cs
  Assets/02. Scripts/02.-04. Sales/1.Domain/SalesDTO.cs
  Assets/02. Scripts/02.-04. Sales/3.Manager/SalesManager.cs
  Assets/03. Prefabs/Scene UI/LobbyScene/Shop/Slot_Shop.prefab
Labels: Feature, 🍉Mingyu

#190 Fix | BGM 추가 및 waiting scene, game scene 미연결 문제 해결
  Assets/01. Scenes/Beta Scenes/GameScene_Tier1PotionShop.unity
  Assets/01. Scenes/Beta Scenes/LobbyScene.unity
  Assets/02. Scripts/02-01. Common/InGameBGM.cs
  Assets/02. Scripts/02-01. Common/InGameBGM.cs.meta
  Assets/02. Scripts/02-06. Structure/Furniture/Furniture.cs
  Assets/02. Scripts/02-07. NewsPaper/UI_NewsPaper.cs
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/LobbyScene.cs
  Assets/02. Scripts/02-20. SceneLogic/WaitingScene/WaitingScene.cs
  Assets/02. Scripts/02. Phase/UI_Phase.cs
  Assets/02. Scripts/Audio/AudioManager.cs
  Assets/03. Prefabs/======= [ NetworkFactorysDDOL ] =======.prefab
  Assets/03. Prefabs/BGM.prefab
  Assets/03. Prefabs/BGM.prefab.meta
  Assets/03. Prefabs/Recipe/UI_RecipeBook.prefab
  Assets/09. SFXs/AudioMixer.mixer
  Assets/09. SFXs/BGM.meta
  Assets/09. SFXs/BGM/SFX_BGM_InGamePreparing.wav
  Assets/09. SFXs/BGM/SFX_BGM_InGamePreparing.wav.meta
  Assets/09. SFXs/BGM/SFX_BGM_InGameServing.wav
  Assets/09. SFXs/BGM/SFX_BGM_InGameServing.wav.meta
  Assets/09. SFXs/BGM/SFX_BGM_LobbyScene.wav
  Assets/09. SFXs/BGM/SFX_BGM_LobbyScene.wav.meta
Labels: Add, Fix, 🍪Sangjin, Chore

#199 Style npc UI폴리싱
  Assets/02. Scripts/02-10. Customer/CustomerAbility/CustomerEndurance.cs
  Assets/02. Scripts/02-10. Customer/CustomerAbility/CustomerMove.cs
  Assets/02. Scripts/02-10. Customer/CustomerUI/UI_Customer.cs
  Assets/03. Prefabs/Customer/CustomerNPC.prefab
  Assets/20. External Assets/Epic Toon FX/Materials/Basics/glow4_ADD.mat
  Assets/20. External Assets/Epic Toon FX/Materials/Misc/Emojis/em_angry.mat
  Assets/20. External Assets/Epic Toon FX/Materials/Misc/Emojis/em_angryscream.mat
  Assets/20. External Assets/Epic Toon FX/Materials/Misc/Emojis/em_bigsmile.mat
  Assets/20. External Assets/Epic Toon FX/Materials/Misc/Emojis/em_blush.mat
  Assets/20. External Assets/Epic Toon FX/Materials/Misc/Emojis/em_clenchteeth.mat
  Assets/20. External Assets/Epic Toon FX/Materials/Misc/Emojis/em_crazy.mat
  Assets/20. External Assets/Epic Toon FX/Materials/Misc/Emojis/em_cry.mat
  Assets/20. External Assets/Epic Toon FX/Materials/Misc/Emojis/em_derpgasp.mat
  Assets/20. External Assets/Epic Toon FX/Materials/Misc/Emojis/em_disappoint.mat
  Assets/20. External Assets/Epic Toon FX/Materials/Misc/Emojis/em_nauseous.mat
  Assets/20. External Assets/Epic Toon FX/Materials/Misc/Emojis/em_pleading.mat
  Assets/20. External Assets/Epic Toon FX/Materials/Misc/Emojis/em_scared.mat
  Assets/20. External Assets/Epic Toon FX/Materials/Misc/Emojis/em_shocked.mat
  Assets/20. External Assets/Epic Toon FX/Materials/Misc/Emojis/em_sick.mat
  Assets/20. External Assets/Epic Toon FX/Materials/Misc/Emojis/em_sick2.mat
  Assets/20. External Assets/Epic Toon FX/Materials/Misc/Emojis/em_sick3.mat
  Assets/20. External Assets/Epic Toon FX/Materials/Misc/Emojis/em_sleep.mat
  Assets/20. External Assets/Epic Toon FX/Materials/Misc/Emojis/em_yawn.mat
  Assets/20. External Assets/Epic Toon FX/Materials/Misc/Liquid/splat03_3x3_AB.mat
  CCDBuildData/ManagedEnvironment/ManagedBucket/ManagedBadge/6be9f241b1e8057595b8143dbca97c6a_monoscripts_3e23375cbe6b6d76dfc99a981aa683e8.bundle
  CCDBuildData/ManagedEnvironment/ManagedBucket/ManagedBadge/6be9f241b1e8057595b8143dbca97c6a_monoscripts_a6c4f9761bb029298619eaa46b843c1b.bundle
  CCDBuildData/ManagedEnvironment/ManagedBucket/ManagedBadge/catalog_0.1.0.hash
  CCDBuildData/ManagedEnvironment/ManagedBucket/ManagedBadge/catalog_0.1.0.json
Labels: 🍎Yeongsuk, Style

#200 Fix | UI key input수정, 완성 - 박우영
  Assets/01. Scenes/Beta Scenes/GameScene_Tier1PotionShop.unity
  Assets/01. Scenes/Beta Scenes/LobbyScene.unity
  Assets/02. Scripts/02-01. Common/Input/UI_ButtonAutoNavigator.cs
  Assets/02. Scripts/02-01. Common/Input/UI_FirstButtonSelector.cs
  Assets/02. Scripts/02-01. Common/Input/UI_NavigationLinker.cs
  Assets/02. Scripts/02-03. Player/Ability/PlayerPingAbility.cs
  Assets/02. Scripts/02-05. Product/3.Manager/ProductImageHelper.cs
  Assets/02. Scripts/02-05. Product/4.UI/UI_DetailPage.cs
  Assets/02. Scripts/02-05. Product/4.UI/UI_Market.cs
  Assets/02. Scripts/02-05. Product/4.UI/UI_ProductSlot.cs
  Assets/02. Scripts/02-11. Recipe/4. UI/UI_RecipeBook.cs
  Assets/02. Scripts/02-20. SceneLogic/GameScene/GameSceneUIManager.cs
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/LobbySceneUIManager.cs
  Assets/02. Scripts/02-20. SceneLogic/LobbyScene/LobbySceneUIManager.cs.meta
  Assets/03. Prefabs/Product/NEW/Popup_Market.prefab
  Assets/03. Prefabs/Product/NEW/UI_Market.prefab
  Assets/03. Prefabs/Product/NEW/UI_ProductSlot.prefab
  Assets/03. Prefabs/Recipe/Popup_RecipeBook.prefab
  Assets/03. Prefabs/Recipe/UI_RecipeBook.prefab
  Assets/03. Prefabs/Scene UI/LobbyScene/Popup/Popup_Newspaper.prefab
  Assets/03. Prefabs/Scene UI/LobbyScene/Popup/Popup_Settings_InGame.prefab
Labels: Feature, Fix, 🍞Uyeong

#202 Feat | 로딩씬 조작키 안내
  Assets/01. Scenes/Beta Scenes/LoadingSceneToGameScene.unity
  Assets/02. Scripts/02-01. Common/Input/InputManager.cs
  Assets/02. Scripts/02-01. Common/Input/UI_ShowBindedKey.cs
  Assets/02. Scripts/02-20. SceneLogic/LoadingScene/UI_KeyGuide.cs
  Assets/02. Scripts/02-20. SceneLogic/LoadingScene/UI_KeyGuide.cs.meta
  Assets/03. Prefabs/Scene UI/LoadingScene/KeyGuide.prefab
  Assets/03. Prefabs/Scene UI/LoadingScene/KeyGuide.prefab.meta
  Assets/03. Prefabs/Scene UI/LoadingScene/UI_LoadingScene.prefab
Labels: Feature, 🍉Mingyu

#203 Style | 마켓 버튼 하이라이트/셀렉트 색상변경 / 코인 이미지 변경 - 심형준
  Assets/01. Scenes/Beta Scenes/GameScene_Tier1PotionShop.unity
  Assets/03. Prefabs/Product/NEW/Popup_Market.prefab
  Assets/03. Prefabs/Product/NEW/UI_ProductSlot.prefab
  Assets/03. Prefabs/Scene UI/GameScene/PhaseHUDCanvas.prefab
  Assets/09. SFXs/AudioMixer.mixer
Labels: 🧃Hyeongjun, Style

#207 Refactor | 들기내려놓기 관련 미사용코드 정리
  Assets/02. Scripts/02-01. Common/GridItemHandler/IGridItemHandler.cs
  Assets/02. Scripts/02-06. Structure/Furniture/Furniture.cs
  Assets/02. Scripts/02-06. Structure/Machine/Machine.cs
  Assets/02. Scripts/02-06. Structure/Storage/Storage.cs
Labels: Refactor, 🧃Hyeongjun

#209 Fix | 인풋맵핑매니저 위치 수정
  Assets/01. Scenes/Beta Scenes/GameScene_Tier1PotionShop.unity
  Assets/02. Scripts/02-01. Common/TooltipManager.cs
  Assets/02. Scripts/02-01. Common/TooltipManager.cs.meta
  Assets/02. Scripts/02-01. Common/UI_Tooltip.cs
  Assets/02. Scripts/02-01. Common/UI_Tooltip.cs.meta
  Assets/02. Scripts/02-06. Structure/Furniture/Furniture.cs
  Assets/02. Scripts/02-06. Structure/Machine/Machine.cs
  Assets/02. Scripts/02-06. Structure/Storage/Storage.cs
  Assets/02. Scripts/02-10. Customer/CustomerAbility/CustomerEndurance.cs
  Assets/02. Scripts/02. Phase/Phases/ServingPhase.cs
  Assets/03. Prefabs/Furniture/Machine.prefab
  Assets/03. Prefabs/Scene UI/GameScene/PhaseHUDCanvas.prefab
  Assets/03. Prefabs/Scene UI/GameScene/TooltipPanels.prefab
  Assets/03. Prefabs/Scene UI/GameScene/TooltipPanels.prefab.meta
Labels: 🍪Sangjin, Chore

#204 Fix | NPC가 중앙을 향해 이동하게 수정
  Assets/01. Scenes/Beta Scenes/GameScene_Tier1PotionShop.unity
  Assets/01. Scenes/Beta Scenes/GameScene_Tier1PotionShop/NavMesh-======= [ Maps ] =======.asset
  Assets/02. Scripts/02-05. Grid/1. Domain/GridData.cs
  Assets/02. Scripts/02-05. Grid/3. Service/GridManager.cs
  Assets/02. Scripts/02-10. Customer/CustomerAbility/CustomerMove.cs
  Assets/02. Scripts/02-10. Customer/CustomerManager/CustomerManager.cs
  Assets/03. Prefabs/Customer/CustomerNPC.prefab
  Assets/03. Prefabs/Furniture/Furniture.prefab
  Assets/03. Prefabs/Potion Process/Potions/Potion_Base.prefab
  ProjectSettings/DynamicsManager.asset
  ProjectSettings/NavMeshAreas.asset
  ProjectSettings/TagManager.asset
Labels: Fix, 🍎Yeongsuk

#210 Fix | 머신 가루 색 변경
  Assets/01. Scenes/Beta Scenes/GameScene_Tier1PotionShop.unity
  Assets/03. Prefabs/Furniture/Machine.prefab
Labels: Fix, 🍎Yeongsuk

#217 Fix | InputField Mouse 움직이면 풀리는 에러 수정 - 박우영
  Assets/02. Scripts/02-01. Common/Input/UI_FirstButtonSelector.cs
Labels: Fix, 🍞Uyeong

#218 Feat | UI Market Slot 클릭 시 Buy Button으로 움직이는 기능 구현
  Assets/02. Scripts/02-01. Common/Input/UI_ButtonAutoNavigator.cs
  Assets/03. Prefabs/Product/NEW/Popup_Market.prefab
Labels: Feature, 🍞Uyeong

#219 Fix | 정산 UI 수정
  Assets/02. Scripts/02.-04. Sales/3.Manager/SalesManager.cs
  Assets/02. Scripts/02.-04. Sales/4.UI/UI_SuccessSummary.cs
Labels: Fix, 🍎Yeongsuk, 🧃Hyeongjun
