Repository Project-PotionMaker/PotionMaker, pull requests merged in 2025-07, with the labels that each got.

#1 Hotfix | 프로젝트 폴더 구조 변경에 따른 Enum Generator Enum 생성 디렉토리 수정
  Assets/Editor/LayerEnumGenerator.cs
  Assets/Editor/SceneEnumGenerator.cs
  Assets/Editor/TagEnumGenerator.cs
Labels: Fix, 🍉Mingyu

#4 Feat | 포션ID 비교 시스템 구현
  .editorconfig
  Assets/02. Scripts/02-04. Potion/ID.meta
  Assets/02. Scripts/02-04. Potion/ID/RecipeCodeTrie.cs
  Assets/02. Scripts/02-04. Potion/ID/RecipeCodeTrie.cs.meta
  Assets/02. Scripts/02-04. Potion/ID/RecipeCodeVerifier.cs
  Assets/02. Scripts/02-04. Potion/ID/RecipeCodeVerifier.cs.meta
Labels: Feature, 🍉Mingyu

#6 Feat | Base Object Pool구현 박우영
  Assets/02. Scripts/02-01. Common/ObjectPool.meta
  Assets/02. Scripts/02-01. Common/ObjectPool/BaseFactory.cs
  Assets/02. Scripts/02-01. Common/ObjectPool/BaseFactory.cs.meta
  Assets/02. Scripts/02-01. Common/ObjectPool/BasePoolInfo.cs
  Assets/02. Scripts/02-01. Common/ObjectPool/BasePoolInfo.cs.meta
  Assets/02. Scripts/02-01. Common/ObjectPool/BasePoolManager.cs
  Assets/02. Scripts/02-01. Common/ObjectPool/BasePoolManager.cs.meta
Labels: Feature, 🍞Uyeong

#7 FEAT | Enum 시트 연동 시스템 구현
  Assets/01. Scenes/EnumTestScene.unity
  Assets/01. Scenes/EnumTestScene.unity.meta
  Assets/02. Scripts/02-01. Common/Data/EnumDef.cs
  Assets/02. Scripts/02-01. Common/Data/EnumDef.cs.meta
  Assets/02. Scripts/02-01. Common/Data/MachineData.cs
  Assets/Editor Default Resources/DataTable/MachineData.txt
  Assets/Editor/DataExporterEditor/DataExporterEditor.Export.cs
  Assets/Editor/DataExporterEditor/DataExporterEditor.cs
  Assets/NuGet.config.meta
  Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  Assets/Resources/DataTable/MachineData.bytes
Labels: Feature, 🍪Sangjin

#8 Feat | 판매 관리
  Assets/01. Scenes/CurrencyScene.unity
  Assets/02. Scripts/02-03. Currency/CurrencyTest.cs
  Assets/02. Scripts/02.-04. Sales.meta
  Assets/02. Scripts/02.-04. Sales/1.Domain.meta
  Assets/02. Scripts/02.-04. Sales/1.Domain/Sales.cs
  Assets/02. Scripts/02.-04. Sales/1.Domain/Sales.cs.meta
  Assets/02. Scripts/02.-04. Sales/1.Domain/SalesDTO.cs
  Assets/02. Scripts/02.-04. Sales/1.Domain/SalesDTO.cs.meta
  Assets/02. Scripts/02.-04. Sales/1.Domain/SalesRPCData.cs
  Assets/02. Scripts/02.-04. Sales/1.Domain/SalesRPCData.cs.meta
  Assets/02. Scripts/02.-04. Sales/2.Repository.meta
  Assets/02. Scripts/02.-04. Sales/3.Manager.meta
  Assets/02. Scripts/02.-04. Sales/3.Manager/SalesManager.cs
  Assets/02. Scripts/02.-04. Sales/3.Manager/SalesManager.cs.meta
  Assets/02. Scripts/02.-04. Sales/4.UI.meta
  Assets/02. Scripts/02.-04. Sales/4.UI/UI_Sales.cs
  Assets/02. Scripts/02.-04. Sales/4.UI/UI_Sales.cs.meta
  Assets/02. Scripts/02.-04. Sales/4.UI/UI_SalesVolumeSlot.cs
  Assets/02. Scripts/02.-04. Sales/4.UI/UI_SalesVolumeSlot.cs.meta
  Assets/03. Prefabs/SalesManager.prefab
  Assets/03. Prefabs/SalesManager.prefab.meta
  Assets/03. Prefabs/UI_Sales.prefab
  Assets/03. Prefabs/UI_Sales.prefab.meta
  Assets/03. Prefabs/UI_SalesVolumeSlot.prefab
  Assets/03. Prefabs/UI_SalesVolumeSlot.prefab.meta
  Assets/AddressableAssetsData/ProfileDataSourceSettings.asset
  Assets/AddressableAssetsData/ProfileDataSourceSettings.asset.meta
  Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  Assets/Settings/UniversalRenderPipelineGlobalSettings.asset
Labels: Feature, 🧃Hyeongjun

#10 Fix | 총판매량 버그 수정 및 SetSales 유효성 검사 추가
  Assets/02. Scripts/02.-04. Sales/1.Domain/Sales.cs
Labels: Fix, 🧃Hyeongjun

#19 Feat | Machine 클래스 구현 이상진
  Assets/01. Scenes/LSJ_GridTestScene.unity
  Assets/02. Scripts/02-01. Common/Data/DataTable.cs
  Assets/02. Scripts/02-01. Common/Data/EnumDef.cs
  Assets/02. Scripts/02-01. Common/Data/InputData.cs
  Assets/02. Scripts/02-01. Common/Data/InputData.cs.meta
  Assets/02. Scripts/02-01. Common/Data/MachineData.cs
  Assets/02. Scripts/02-01. Common/Data/OutputData.cs
  Assets/02. Scripts/02-01. Common/Data/ProductData.cs
  Assets/02. Scripts/02-01. Common/Data/ProductData.cs.meta
  Assets/02. Scripts/02-01. Common/Enum/EAddressables.cs
  Assets/02. Scripts/02-01. Common/Global/Global.cs
  Assets/02. Scripts/02-01. Common/IInteractable.cs
  Assets/02. Scripts/02-01. Common/IInteractable.cs.meta
  Assets/02. Scripts/02-01. Common/IItemContainer.cs
  Assets/02. Scripts/02-01. Common/IItemContainer.cs.meta
  Assets/02. Scripts/02-05. Grid/3. Service/States/PlacementState.cs
  Assets/02. Scripts/02-05. Grid/LayoutEditing/GridInfo.cs
  Assets/02. Scripts/02-06. Structure/Furniture/Furniture.cs
  Assets/02. Scripts/02-06. Structure/Furniture/Furniture.cs.meta
  Assets/02. Scripts/02-06. Structure/Machine/Classes.meta
  Assets/02. Scripts/02-06. Structure/Machine/Classes/Distiller.cs
  Assets/02. Scripts/02-06. Structure/Machine/Classes/Distiller.cs.meta
  Assets/02. Scripts/02-06. Structure/Machine/Machine.cs
  Assets/02. Scripts/02-06. Structure/Machine/Machine.cs.meta
  Assets/02. Scripts/02-06. Structure/Machine/MachineEntry.cs
  Assets/02. Scripts/02-06. Structure/Machine/MachineEntry.cs.meta
  Assets/02. Scripts/02-06. Structure/Machine/MachineManager.cs
  Assets/02. Scripts/02-06. Structure/StructureManager.cs
  Assets/02. Scripts/02-07. Output.meta
  Assets/02. Scripts/02-07. Output/OutputManager.cs
  Assets/02. Scripts/02-07. Output/OutputManager.cs.meta
  Assets/03. Prefabs/Furniture/Chair.prefab
  Assets/AddressableAssetsData/AddressableAssetSettings.asset
  Assets/AddressableAssetsData/AssetGroups/CCD.asset
  Assets/Editor Default Resources/DataTable/InputData.txt
  Assets/Editor Default Resources/DataTable/InputData.txt.meta
  Assets/Editor Default Resources/DataTable/MachineData.txt
  Assets/Editor Default Resources/DataTable/OutputData.txt
  Assets/Editor Default Resources/DataTable/ProductData.txt
  Assets/Editor Default Resources/DataTable/ProductData.txt.meta
  Assets/Resources/DataTable/InputData.bytes
  Assets/Resources/DataTable/InputData.bytes.meta
  Assets/Resources/DataTable/MachineData.bytes
  Assets/Resources/DataTable/OutputData.bytes
  Assets/Resources/DataTable/ProductData.bytes
  Assets/Resources/DataTable/ProductData.bytes.meta
  CCDBuildData/ManagedEnvironment/ManagedBucket/ManagedBadge/ccd_assets_all_98bacf99814156f6b5efec169bfc177e.bundle
Labels: Feature, 🍪Sangjin

#18 Feat | 포션 제작 프로세스 설계 및 AssetManager 프리팹 캐싱 시스템 구현
  Assets/02. Scripts/02-01. Common/Addressable/AssetManager.cs
  Assets/02. Scripts/02-01. Common/CSharpKeywordUtility.cs
  Assets/02. Scripts/02-01. Common/CSharpKeywordUtility.cs.meta
  Assets/02. Scripts/02-01. Common/Data/DataTable.cs
  Assets/02. Scripts/02-01. Common/Data/EnumDef.cs
  Assets/02. Scripts/02-01. Common/Data/IngredientData.cs
  Assets/02. Scripts/02-01. Common/Data/OutputData.cs
  Assets/02. Scripts/02-01. Common/Enum/EAddressableKeys.cs
  Assets/02. Scripts/02-01. Common/Enum/EAddressableKeys.cs.meta
  Assets/02. Scripts/02-01. Common/Enum/EAddressableLabels.cs
  Assets/02. Scripts/02-01. Common/Enum/EAddressableLabels.cs.meta
  Assets/02. Scripts/02-01. Common/Factory/BaseFactoryInfo.cs
  Assets/02. Scripts/02-04. Potion/Ingredient.meta
  Assets/02. Scripts/02-04. Potion/Ingredient/Ingredient.cs
  Assets/02. Scripts/02-04. Potion/Ingredient/Ingredient.cs.meta
  Assets/02. Scripts/02-04. Potion/Output.meta
  Assets/02. Scripts/02-04. Potion/Output/Factory.meta
  Assets/02. Scripts/02-04. Potion/Output/Factory/OutputFactoryInfo.cs
  Assets/02. Scripts/02-04. Potion/Output/Factory/OutputFactoryInfo.cs.meta
  Assets/02. Scripts/02-04. Potion/Output/Factory/OutputPool.cs
  Assets/02. Scripts/02-04. Potion/Output/Factory/OutputPool.cs.meta
  Assets/02. Scripts/02-04. Potion/Output/Output.cs
  Assets/02. Scripts/02-04. Potion/Output/Output.cs.meta
  Assets/02. Scripts/02-04. Potion/Output/OutputManager.cs
  Assets/02. Scripts/02-04. Potion/Output/OutputManager.cs.meta
  Assets/02. Scripts/02-04. Potion/Potion.meta
  Assets/02. Scripts/02-04. Potion/Potion/Potion.cs
  Assets/02. Scripts/02-04. Potion/Potion/Potion.cs.meta
  Assets/02. Scripts/02-04. Potion/RecipeCode.meta
  Assets/02. Scripts/02-04. Potion/RecipeCode/RecipeCodeHandler.cs
  Assets/02. Scripts/02-04. Potion/RecipeCode/RecipeCodeHandler.cs.meta
  Assets/02. Scripts/02-04. Potion/RecipeCode/RecipeCodeTrie.cs
  Assets/02. Scripts/02-04. Potion/RecipeCode/RecipeCodeTrie.cs.meta
  Assets/02. Scripts/02-04. Potion/RecipeCode/RecipeCodeVerifier.cs
  Assets/02. Scripts/02-04. Potion/RecipeCode/RecipeCodeVerifier.cs.meta
  Assets/02. Scripts/02-06. Structure/Machine/Classes/Distiller.cs
  Assets/02. Scripts/02-07. Output/OutputManager.cs
  Assets/Editor Default Resources/DataTable/IngredientData.txt
  Assets/Editor Default Resources/DataTable/OutputData.txt
  Assets/Editor/EnumGenerator/AddressableEnumGenerator.cs
  Assets/Resources/DataTable/IngredientData.bytes
  Assets/Resources/DataTable/OutputData.bytes
Labels: Feature, 🍉Mingyu

#23 Feat | Input system구현 박우영
  Assets/01. Scenes/InputScene_WYP.unity
  Assets/01. Scenes/InputScene_WYP.unity.meta
  Assets/02. Scripts/02-01. Common/Enum/EAddressableKeys.cs
  Assets/02. Scripts/02-03. Player/Ability.meta
  Assets/02. Scripts/02-03. Player/Ability/PlayerAbility.cs
  Assets/02. Scripts/02-03. Player/Ability/PlayerAbility.cs.meta
  Assets/02. Scripts/02-03. Player/Ability/PlayerInteractAbility.cs
  Assets/02. Scripts/02-03. Player/Ability/PlayerInteractAbility.cs.meta
  Assets/02. Scripts/02-03. Player/Ability/PlayerMoveAbility.cs
  Assets/02. Scripts/02-03. Player/Ability/PlayerMoveAbility.cs.meta
  Assets/02. Scripts/02-03. Player/Ability/PlayerPickupAbility.cs
  Assets/02. Scripts/02-03. Player/Ability/PlayerPickupAbility.cs.meta
  Assets/02. Scripts/02-03. Player/Ability/PlayerPingAbility.cs
  Assets/02. Scripts/02-03. Player/Ability/PlayerPingAbility.cs.meta
  Assets/02. Scripts/02-03. Player/Ability/PlayerReadyAbility.cs
  Assets/02. Scripts/02-03. Player/Ability/PlayerReadyAbility.cs.meta
  Assets/02. Scripts/02-03. Player/Input.meta
  Assets/02. Scripts/02-03. Player/Input/InputManager.cs
  Assets/02. Scripts/02-03. Player/Input/InputManager.cs.meta
  Assets/02. Scripts/02-03. Player/Player.cs
  Assets/02. Scripts/02-03. Player/Player.cs.meta
  Assets/02. Scripts/02-08. Server/RoomManager.cs
  Assets/02. Scripts/02-08. Server/RoomManager.cs.meta
  Assets/03. Prefabs/Player.meta
  Assets/03. Prefabs/Player/Player.prefab
  Assets/03. Prefabs/Player/Player.prefab.meta
  Assets/AddressableAssetsData/AssetGroups/CCD.asset
  Assets/InputSystem_Actions.inputactions
Labels: Feature, Fix, 🍞Uyeong, Style

#26 Fix | Factory 수정 및 Create 함수 오버로드
  Assets/02. Scripts/02-01. Common/Factory/BaseFactory.cs
Labels: Fix, 🍞Uyeong

#27 Fix | 병합 과정에서 발생한 누락 수정
  Assets/02. Scripts/02-01. Common/ItemContainer/DefaultMachineContainer.cs
Labels: Fix, 🍉Mingyu

#35 Feat | 구조물 배치 - 이상진
  Assets/01. Scenes/LSJ_GridTestScene.unity
  Assets/02. Scripts/02-01. Common/ItemContainer/DefaultMachineContainer.cs
  Assets/02. Scripts/02-01. Common/ItemContainer/IMachineItemContainer.cs
  Assets/02. Scripts/02-03. Player/Ability/PlayerPickupAbility.cs
  Assets/02. Scripts/02-05. Grid/1. Domain/GridData.cs
  Assets/02. Scripts/02-05. Grid/1. Domain/Placement.cs
  Assets/02. Scripts/02-05. Grid/3. Service/GridManager.cs
  Assets/02. Scripts/02-05. Grid/3. Service/GridManager_mouseTest.cs
  Assets/02. Scripts/02-05. Grid/3. Service/PlaceSystem.cs
  Assets/02. Scripts/02-05. Grid/3. Service/PreviewSystem.cs
  Assets/02. Scripts/02-05. Grid/3. Service/States/IBuildingState.cs
  Assets/02. Scripts/02-05. Grid/3. Service/States/PlacementState.cs
  Assets/02. Scripts/02-05. Grid/3. Service/States/RemovingState.cs
  Assets/02. Scripts/02-06. Structure/Machine/Machine.cs
  Assets/02. Scripts/02-06. Structure/StructureManager.cs
Labels: Add, Feature, 🍪Sangjin

#30 Feat | 방세 관리 - 심형준
  Assets/01. Scenes/CurrencyScene.unity
  Assets/02. Scripts/02-01. Common/Global/Global.cs
  Assets/02. Scripts/02-09. Rent.meta
  Assets/02. Scripts/02-09. Rent/1.Domain.meta
  Assets/02. Scripts/02-09. Rent/1.Domain/Rent.cs
  Assets/02. Scripts/02-09. Rent/1.Domain/Rent.cs.meta
  Assets/02. Scripts/02-09. Rent/1.Domain/RentDTO.cs
  Assets/02. Scripts/02-09. Rent/1.Domain/RentDTO.cs.meta
  Assets/02. Scripts/02-09. Rent/1.Domain/RentRPCData.cs
  Assets/02. Scripts/02-09. Rent/1.Domain/RentRPCData.cs.meta
  Assets/02. Scripts/02-09. Rent/3.Manager.meta
  Assets/02. Scripts/02-09. Rent/3.Manager/RentManager.cs
  Assets/02. Scripts/02-09. Rent/3.Manager/RentManager.cs.meta
  Assets/02. Scripts/02-09. Rent/4.UI.meta
  Assets/02. Scripts/02-09. Rent/4.UI/UI_Rent.cs
  Assets/02. Scripts/02-09. Rent/4.UI/UI_Rent.cs.meta
  Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
Labels: Feature, 🧃Hyeongjun

#31 Feat | 재료, 아웃풋, 포션 클래스 데이터 동기화 및 프로토타입용 프리팹 추가
  Assets/01. Scenes/AddressableTestScene_CMG.unity
  Assets/02. Scripts/02-01. Common/ItemContainer/DefaultMachineContainer.cs
  Assets/02. Scripts/02-04. Potion/Ingredient/Ingredient.cs
  Assets/02. Scripts/02-04. Potion/Output/Factory/OutputFactory.cs
  Assets/02. Scripts/02-04. Potion/Output/Factory/OutputFactory.cs.meta
  Assets/02. Scripts/02-04. Potion/Output/Output.cs
  Assets/02. Scripts/02-04. Potion/Output/OutputManager.cs
  Assets/02. Scripts/02-04. Potion/Potion/Potion.cs
  Assets/02. Scripts/02-04. Potion/RecipeCode/RecipeCodeHandler.cs
  Assets/03. Prefabs/Potion Process.meta
  Assets/03. Prefabs/Potion Process/Ingredient.meta
  Assets/03. Prefabs/Potion Process/Ingredient/Ingredient1_Prototype.prefab
  Assets/03. Prefabs/Potion Process/Ingredient/Ingredient1_Prototype.prefab.meta
  Assets/03. Prefabs/Potion Process/Ingredient/Ingredient2_Prototype.prefab
  Assets/03. Prefabs/Potion Process/Ingredient/Ingredient2_Prototype.prefab.meta
  Assets/03. Prefabs/Potion Process/Output.meta
  Assets/03. Prefabs/Potion Process/Output/Output_Prototype.prefab
  Assets/03. Prefabs/Potion Process/Output/Output_Prototype.prefab.meta
  Assets/03. Prefabs/Potion Process/Potion.meta
  Assets/03. Prefabs/Potion Process/Potion/Potion_Prototype.prefab
  Assets/03. Prefabs/Potion Process/Potion/Potion_Prototype.prefab.meta
  Assets/Photon/PhotonUnityNetworking/Demos/DemoSlotRacer/Kenney Assets/Stylized city/Materials/13 - Default22662.mat
  Assets/Photon/PhotonUnityNetworking/Demos/DemoSlotRacer/Kenney Assets/Stylized city/Materials/13 - Default54.mat
  Assets/Photon/PhotonUnityNetworking/Demos/DemoSlotRacer/Kenney Assets/Stylized city/Materials/20 - Default.mat
Labels: Add, Feature, 🍉Mingyu

#47 FEAT | NPC 계산기 상호작용 테스트 완료
  Assets/01. Scenes/LSJ_GridTestScene.unity
  Assets/02. Scripts/02-01. Common/Data/EnumDef.cs
  Assets/02. Scripts/02-01. Common/Enum/EAddressableKeys.cs
  Assets/02. Scripts/02-01. Common/Interactable/CasherInteract.cs
  Assets/02. Scripts/02-01. Common/ItemContainer/PickUpTableInputContainer.cs
  Assets/02. Scripts/02-03. Player/Ability/PlayerInteractAbility.cs
  Assets/02. Scripts/02-05. Grid/3. Service/GridManager.cs
  Assets/02. Scripts/02-06. Structure/Furniture/Furniture.cs
  Assets/02. Scripts/02-06. Structure/Machine/Machine.cs
  Assets/02. Scripts/02-06. Structure/Machine/UI_Machine.cs
  Assets/02. Scripts/02-06. Structure/Storage.cs
  Assets/02. Scripts/02-06. Structure/StructureManager.cs
  Assets/02. Scripts/02. Phase/ServingPhase.cs
  Assets/03. Prefabs/Furniture/Furniture.prefab
  Assets/03. Prefabs/Furniture/Furniture.prefab.meta
  Assets/03. Prefabs/Furniture/Machine.prefab
  Assets/03. Prefabs/Furniture/Machine.prefab.meta
  Assets/03. Prefabs/Furniture/Storage.prefab
  Assets/20. External Assets/KayKit/Packs/KayKit - Dungeon Remastered (for Unity)/Materials/texture.mat
  Assets/20. External Assets/Layer Lab/3D Medieval Pack/URPSettings/Universal Render Pipeline Asset.asset
  Assets/20. External Assets/Modular Dark Wizard Cute Pro Series/Materials/Crow Face 01 Blue.mat
  Assets/20. External Assets/Modular Dark Wizard Cute Pro Series/Materials/Eye 01.mat
  Assets/20. External Assets/Modular Dark Wizard Cute Pro Series/Materials/FX Fire Orange.mat
  Assets/20. External Assets/Modular Dark Wizard Cute Pro Series/Materials/Face 01 Green.mat
  Assets/20. External Assets/Modular Dark Wizard Cute Pro Series/Materials/Face 01 Red.mat
  Assets/20. External Assets/Modular Dark Wizard Cute Pro Series/Materials/Wand 01 Black.mat
  Assets/20. External Assets/Modular Dark Wizard Cute Pro Series/Materials/Wand 01 Purple.mat
  Assets/20. External Assets/Modular Dark Wizard Cute Pro Series/Materials/Wand 01 Red.mat
  Assets/20. External Assets/Modular Dark Wizard Cute Pro Series/Materials/Wizard Black.mat
  Assets/20. External Assets/Modular Dark Wizard Cute Pro Series/Materials/Wizard Purple.mat
  Assets/20. External Assets/Modular Dark Wizard Cute Pro Series/Materials/Wizard Red.mat
  Assets/AddressableAssetsData/AssetGroups/CCD.asset
  Assets/Daniel Mistage/STYLIZED The Alchemist's Workshop - Low Poly 3D Art/Textures and Materials/Materials/GLOW WINDOW.mat
  Assets/Editor Default Resources/DataTable/MachineData.txt
  Assets/Editor Default Resources/DataTable/PotionData.txt
  Assets/Epic Toon FX.meta
  Assets/Epic Toon FX/Upgrade.meta
  Assets/Epic Toon FX/Upgrade/Legacy.meta
  Assets/Feel.meta
  Assets/Feel/FeelDemos.meta
  Assets/Feel/FeelDemosURP.meta
  Assets/Feel/NiceVibrations.meta
  Assets/Feel/NiceVibrations/OlderVersions.meta
  Assets/Feel/NiceVibrations/OlderVersions/v1.7.meta
  Assets/Feel/NiceVibrations/OlderVersions/v2.0.1.meta
  Assets/Feel/NiceVibrations/OlderVersions/v3.9.meta
  Assets/MK.meta
  Assets/MK/MKToon.meta
  Assets/MK/MKToon/Examples.meta
  Assets/Resources/DataTable/MachineData.bytes
  Assets/Resources/DataTable/PotionData.bytes
  CCDBuildData/ManagedEnvironment/ManagedBucket/ManagedBadge/6be9f241b1e8057595b8143dbca97c6a_monoscripts_8c4ded2889e8a37556d224d600a43db8.bundle
  CCDBuildData/ManagedEnvironment/ManagedBucket/ManagedBadge/6be9f241b1e8057595b8143dbca97c6a_unitybuiltinassets_799304739a4c7949b57fb267db52f250.bundle
  CCDBuildData/ManagedEnvironment/ManagedBucket/ManagedBadge/catalog_0.1.0.hash
  CCDBuildData/ManagedEnvironment/ManagedBucket/ManagedBadge/catalog_0.1.0.json
  CCDBuildData/ManagedEnvironment/ManagedBucket/ManagedBadge/ccd_assets_all_6b85e6c27c96b99d3b9987b89e04d6c9.bundle
  CCDBuildData/ManagedEnvironment/ManagedBucket/ManagedBadge/ccd_assets_all_f8c14c52ed86b180d80fb898f29cdfb8.bundle
  CCDBuildData/ManagedEnvironment/ManagedBucket/ManagedBadge/d7b8dd3b28e3ceb768d41ae4ee9adc60_monoscripts_53d73f52480c231620fcd77455d779ab.bundle
  CCDBuildData/ManagedEnvironment/ManagedBucket/ManagedBadge/d7b8dd3b28e3ceb768d41ae4ee9adc60_unitybuiltinassets_2455051c2cc01bfc2d5256e8a568f95f.bundle
Labels: Feature, 🍪Sangjin

#50 Add | 프로토타입용 리소스추가
  Assets/02. Scripts/02-04. Potion/CraftItem/PotionItem/PotionItem.cs
  Assets/02. Scripts/02-05. Grid/3. Service/GridManager.cs
  Assets/03. Prefabs/Potion Process/Ingredients/Ingredient_Base.prefab
Labels: Add, 🍉Mingyu

#41 Add | UI기능구현 프리팹화
  Assets/01. Scenes/KYS_NPCGridTestScene.unity
  Assets/02. Scripts/02-10. Customer.meta
  Assets/02. Scripts/02-10. Customer/Customer.cs
  Assets/02. Scripts/02-10. Customer/Customer.cs.meta
  Assets/02. Scripts/02-10. Customer/CustomerAbility.meta
  Assets/02. Scripts/02-10. Customer/CustomerAbility/CustomerEndurance.cs
  Assets/02. Scripts/02-10. Customer/CustomerAbility/CustomerEndurance.cs.meta
  Assets/02. Scripts/02-10. Customer/CustomerAbility/CustomerMove.cs
  Assets/02. Scripts/02-10. Customer/CustomerAbility/CustomerMove.cs.meta
  Assets/02. Scripts/02-10. Customer/CustomerManager.meta
  Assets/02. Scripts/02-10. Customer/CustomerManager/CustomerLineHandler.cs
  Assets/02. Scripts/02-10. Customer/CustomerManager/CustomerLineHandler.cs.meta
  Assets/02. Scripts/02-10. Customer/CustomerManager/CustomerManager.cs
  Assets/02. Scripts/02-10. Customer/CustomerManager/CustomerManager.cs.meta
  Assets/02. Scripts/02-10. Customer/CustomerManager/CustomerOrderHandler.cs
  Assets/02. Scripts/02-10. Customer/CustomerManager/CustomerOrderHandler.cs.meta
  Assets/02. Scripts/02-10. Customer/CustomerPool.meta
  Assets/02. Scripts/02-10. Customer/CustomerPool/CustomerFactory.cs
  Assets/02. Scripts/02-10. Customer/CustomerPool/CustomerFactory.cs.meta
  Assets/02. Scripts/02-10. Customer/CustomerPool/CustomerFactoryInfo.cs
  Assets/02. Scripts/02-10. Customer/CustomerPool/CustomerFactoryInfo.cs.meta
  Assets/02. Scripts/02-10. Customer/CustomerPool/CustomerPool.cs
  Assets/02. Scripts/02-10. Customer/CustomerPool/CustomerPool.cs.meta
  Assets/02. Scripts/02-10. Customer/CustomerPool/CustomerPoolInfo.cs
  Assets/02. Scripts/02-10. Customer/CustomerPool/CustomerPoolInfo.cs.meta
  Assets/02. Scripts/02-10. Customer/CustomerUI.meta
  Assets/02. Scripts/02-10. Customer/CustomerUI/UI_Customer.cs
  Assets/02. Scripts/02-10. Customer/CustomerUI/UI_Customer.cs.meta
  Assets/02. Scripts/02-10. Customer/UnitTestForCustomer.cs
  Assets/02. Scripts/02-10. Customer/UnitTestForCustomer.cs.meta
  Assets/03. Prefabs/Phase/PhaseHUDCanvas.prefab
  Assets/03. Prefabs/Phase/PhaseHUDCanvas.prefab.meta
Labels: Add, Documentation, 🍎Yeongsuk

#54 Style 일과UI에셋적용
  Assets/01. Scenes/KYS_NPCGridTestScene.unity
  Assets/02. Scripts/02. Phase/UI_Phase.cs
  Assets/03. Prefabs/Customer/CustomerNPC.prefab
  Assets/03. Prefabs/Phase/PhaseHUDCanvas.prefab
  Assets/06. Animations/Customer.meta
  Assets/06. Animations/Customer/Customer.controller
  Assets/06. Animations/Customer/Customer.controller.meta
  Assets/20. External Assets/Free Burrow Cute Series/Cute series demo assets/Ground.mat
  Assets/20. External Assets/Free Burrow Cute Series/FBX/Free Burrow.controller
  Assets/20. External Assets/Free Burrow Cute Series/Materials/Free Burrow.mat
Labels: Add, 🍎Yeongsuk, Style

#57 Feat | customer가 포션 가져가기, 주문 미리받기 막음
  Assets/02. Scripts/02-10. Customer/Customer.cs
  Assets/02. Scripts/02-10. Customer/CustomerManager/CustomerManager.cs
  Assets/02. Scripts/02-10. Customer/UnitTestForCustomer.cs
  Assets/02. Scripts/02. Phase/UI_Phase.cs
  Assets/03. Prefabs/Customer/CustomerNPC.prefab
Labels: Feature, 🍎Yeongsuk

#65 Feat | 포션 뽑기 시스템
  Assets/02. Scripts/02-01. Common/Data/EnumDef.cs
  Assets/02. Scripts/02-01. Common/Data/LayoutData.cs
  Assets/02. Scripts/02-01. Common/Data/PotionData.cs
  Assets/02. Scripts/02-04. Potion/DailyPotion.meta
  Assets/02. Scripts/02-04. Potion/DailyPotion/DailyPotionPicker.cs
  Assets/02. Scripts/02-04. Potion/DailyPotion/DailyPotionPicker.cs.meta
  Assets/02. Scripts/02-04. Potion/RecipeCode/RecipeCodeTrie.cs
  Assets/02. Scripts/02-15. Reputation/3. Manager/ReputationManager.cs
  Assets/Editor Default Resources/DataTable/FurnitureData.txt
  Assets/Editor Default Resources/DataTable/IngredientData.txt
  Assets/Editor Default Resources/DataTable/LayoutData.txt
  Assets/Editor Default Resources/DataTable/MachineData.txt
  Assets/Editor Default Resources/DataTable/OutputData.txt
  Assets/Editor Default Resources/DataTable/PotionData.txt
  Assets/Editor Default Resources/DataTable/StructureData.txt
  Assets/Resources/DataTable/FurnitureData.bytes
  Assets/Resources/DataTable/IngredientData.bytes
  Assets/Resources/DataTable/LayoutData.bytes
  Assets/Resources/DataTable/MachineData.bytes
  Assets/Resources/DataTable/OutputData.bytes
  Assets/Resources/DataTable/PotionData.bytes
  Assets/Resources/DataTable/StructureData.bytes
Labels: Feature, 🍉Mingyu

#68 Fix | BaseFactory 에러 수정
  Assets/02. Scripts/02-01. Common/Factory/BaseFactory.cs
Labels: Fix, 🍞Uyeong

#70 Add | NPC Animation 추가
  Assets/06. Animations/Customer/Burrow@Idle.fbx
  Assets/06. Animations/Customer/Burrow@Idle.fbx.meta
  Assets/06. Animations/Customer/Burrow@Sit.fbx
  Assets/06. Animations/Customer/Burrow@Sit.fbx.meta
  Assets/06. Animations/Customer/Materials.meta
  Assets/06. Animations/Customer/Materials/Lit.mat
  Assets/06. Animations/Customer/Materials/Lit.mat.meta
Labels: Add, 🍞Uyeong

#74 Refactor | AddressableKey Enum Generator 개선
  Assets/02. Scripts/02-01. Common/Enum/EAddressableKeys.cs
  Assets/Editor/EnumGenerator/AddressableEnumGenerator.cs
Labels: Refactor, 🍉Mingyu

#78 Feat | 상점UI 초안 이상진
  Assets/01. Scenes/Prototype Scenes/LSJ_ShopUITest.unity
  Assets/01. Scenes/Prototype Scenes/LSJ_ShopUITest.unity.meta
  Assets/20. External Assets/Layer Lab/GUI Pro-FantasyRPG/Prefabs/Prefabs_Component_Buttons/Button_Circle01-Group.prefab
  Assets/20. External Assets/Layer Lab/GUI Pro-FantasyRPG/Prefabs/Prefabs_Component_Frames/_Prefabs_Frames.prefab
  Assets/20. External Assets/Layer Lab/GUI Pro-FantasyRPG/ResourcesData/Fonts/Alata-Regular SDF.asset
  Assets/20. External Assets/Layer Lab/GUI Pro-FantasyRPG/ResourcesData/Sprites/Component/Frame/LineFrame_03.png.meta
  Assets/20. External Assets/Layer Lab/GUI Pro-FantasyRPG/ResourcesData/Sprites/Component/Label-Title/Label_Tapered_Border_32_Bg.png.meta
  Assets/20. External Assets/Layer Lab/GUI Pro-FantasyRPG/ResourcesData/Sprites/Component/Label-Title/Label_Tapered_Border_32_Deco.png.meta
  Assets/AddressableAssetsData/AddressableAssetSettings.asset
Labels: Add, 🍪Sangjin

#77 HotFix | StartService버튼 다시 작동하게, 인내심도 다시 작동하게
  Assets/02. Scripts/02-05. Grid/3. Service/GridManager.cs
  Assets/02. Scripts/02-10. Customer/CustomerAbility/CustomerEndurance.cs
  Assets/02. Scripts/02-10. Customer/CustomerAbility/CustomerMove.cs
  Assets/02. Scripts/02-10. Customer/CustomerManager/CustomerManager.cs
  Assets/02. Scripts/02-10. Customer/CustomerUI/UI_Customer.cs
  Assets/03. Prefabs/Phase/PhaseHUDCanvas.prefab
  Assets/03. Prefabs/Phase/PhaseManager.prefab
Labels: Fix, 🍎Yeongsuk

#82 Add | 벽, 문 모델 추가
  Assets/01. Scenes/Prototype Scenes/WYP_PrototypeScene.unity
  Assets/03. Prefabs/Furniture/Wooden_Door.prefab
  Assets/03. Prefabs/Furniture/Wooden_Door.prefab.meta
  Assets/03. Prefabs/Furniture/Wooden_Wall.prefab
  Assets/03. Prefabs/Furniture/Wooden_Wall.prefab.meta
  Assets/04. Images/Wall.meta
  Assets/04. Images/Wall/WoodenDoor_Base.jpg
  Assets/04. Images/Wall/WoodenDoor_Base.jpg.meta
  Assets/04. Images/Wall/WoodenDoor_NormalMap.jpg
  Assets/04. Images/Wall/WoodenDoor_NormalMap.jpg.meta
  Assets/04. Images/Wall/WoodenWall_Base.jpg
  Assets/04. Images/Wall/WoodenWall_Base.jpg.meta
  Assets/04. Images/Wall/WoodenWall_NormalMap.png
  Assets/04. Images/Wall/WoodenWall_NormalMap.png.meta
  Assets/07. Materials/Wall.meta
  Assets/07. Materials/Wall/WoodenDoorMaterial.mat
  Assets/07. Materials/Wall/WoodenDoorMaterial.mat.meta
  Assets/07. Materials/Wall/WoodenWallMaterial.mat
  Assets/07. Materials/Wall/WoodenWallMaterial.mat.meta
  Assets/10. Models.meta
  Assets/10. Models/Wall.meta
  Assets/10. Models/Wall/Wooden_Door.fbx
  Assets/10. Models/Wall/Wooden_Door.fbx.meta
  Assets/10. Models/Wall/Wooden_Wall.fbx
  Assets/10. Models/Wall/Wooden_Wall.fbx.meta
Labels: Add, 🍞Uyeong
